# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7358b3fd2e842e162aa357c8c8908c63b387de651be1274abede20f250ae6e7044b3751cd314c47f0b76ec2ec83197e70f55f8be410a120057d28372a00f1a83

test:
  secret_key_base: 339f0775ec490fb328f29b7bd4acaef59323e114d664916eeca00e9134fb815837184af3d797bbc68ccf084d71265e0c17fea5f5187e59d9533bfc8d4a0c264e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
